export const PASSOS_CONTEUDO = {
  1: {
    titulo: "Deus nos Criou",
    fase: "FASE 1: O Evangelho",
    objetivo: "Entender que a vida não é um acidente: fomos criados por Deus com propósito.",
    conteudo: [
      "Deus é o Criador de todas as coisas.",
      "Ele nos fez à Sua imagem (Gênesis 1:26-27).",
      "Isso significa que:",
      "• Temos valor",
      "• Temos identidade",
      "• Fomos criados para nos relacionar com Ele",
      "Você não é um acaso.",
      "Você existe porque Deus desejou a sua vida.",
    ],
    versiculos: [{ texto: "No princípio, criou Deus os céus e a terra.", referencia: "Gênesis 1:1" }],
    videos: [
      {
        id: "video-1",
        titulo: "O que significa ser criado à imagem de Deus?",
        canal: "Cristãos na Ciência",
        duracao: "9:33",
        url: "https://www.youtube.com/watch?v=rr6k9AVyO1Y",
      },
      {
        id: "video-2",
        titulo: "Gênesis 1 - A Criação",
        canal: "Israel da Costa Homem",
        duracao: "7:14",
        url: "https://www.youtube.com/watch?v=uwjM5q6H3Vo&list=RDuwjM5q6H3Vo&start_radio=1",
      },
      {
        id: "video-3",
        titulo: "Por que Deus nos Criou?",
        canal: "Primo Cast",
        duracao: "6:29",
        url: "https://www.youtube.com/watch?v=476WjoLrND0",
      },
    ],
    artigos: [
      {
        id: "artigo-1",
        titulo: "Imago Dei (Imagem de Deus)",
        fonte: "Teólogo Internacional",
        url: "https://teologointernacional.com.br/o-que-significa-ser-criado-a-imagem-e-semelhanca-de-deus-estudos-biblicos/",
      },
      {
        id: "artigo-2",
        titulo: "Fomos Criados para Relacionamento",
        fonte: "fhopchurch",
        url: "https://fhop.com/criados-para-relacionamento/",
      },
      {
        id: "artigo-3",
        titulo: "Criação (Cristianismo)",
        fonte: "Bibliaon",
        url: "https://www.bibliaon.com/os_dias_da_criacao/",
      },
    ],
    perguntaChave: "Qual o propósito da criação do ser humano?",
    missao: 'Escreva uma frase respondendo: "Por que eu existo?"',
    recompensa: "Identidade dada por Deus",
    icone: "✨",
    xp: 100,
  },
  2: {
    titulo: "Deus nos Ama",
    fase: "FASE 1: O Evangelho",
    objetivo: "Reconhecer que o amor de Deus é a base do discipulado e o fundamento de todo relacionamento com Ele.",
    conteudo: [
      "Deus não apenas nos criou, mas nos ama profundamente.",
      "Esse amor é constante, imutável e demonstrado através de suas ações na história.",
      "O maior ato desse amor foi enviar Seu Filho Jesus Cristo para restaurar nossa relação com Ele.",
      "Base bíblica:",
      "- João 3:16 — Porque Deus amou o mundo de tal maneira…",
      "- Romanos 5:8 — Mas Deus prova o seu amor para conosco…",
      "- 1 João 4:7-10 — Deus é amor.",
      "O discipulado não começa com medo, pressão ou religião, mas com amor.",
    ],
    versiculos: [
      {
        texto:
          "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.",
        referencia: "João 3:16",
      },
    ],
    videos: [
      {
        id: "video-p2-1",
        titulo: "Deus te ama – resumo bíblico",
        canal: "Primo Cast",
        duracao: "0:40",
        url: "https://www.youtube.com/watch?v=UxkmVtpk2m0",
      },
      {
        id: "video-p2-2",
        titulo: "O que é o amor de Deus? (Explicação simples)",
        canal: "Luciano Subirá",
        duracao: "11:53",
        url: "https://www.youtube.com/watch?v=eER6r_Qyq1Y",
      },
      {
        id: "video-p2-3",
        titulo: "O Maravilho Amor de Deus",
        canal: "Desenhando a Bíblia",
        duracao: "4:45",
        url: "https://www.youtube.com/watch?v=VO5YhS9ErDc",
      },
    ],
    artigos: [
      {
        id: "artigo-p2-1",
        titulo: "Amor de Deus (Cristianismo)",
        fonte: "PADD",
        url: "https://peloamordedeus.org.br/o-amor-cristao/",
      },
      {
        id: "artigo-p2-2",
        titulo: "João 3:16 – contexto",
        fonte: "O pregador",
        url: "https://opregador.com/esboco-de-pregacao-sobre-joao-316/",
      },
      {
        id: "artigo-p2-3",
        titulo: "Natureza de Deus – Deus é Amor",
        fonte: "Sobre Pregação",
        url: "https://sobrepregacao.com/2024/03/pregacao-sobre-joao-316-porque-deus-amou-o-mundo-de-tal-maneira-que/",
      },
    ],
    perguntaChave: "Como você descreveria o amor de Deus por você, de forma pessoal?",
    missao:
      'Escrever uma pequena carta (5 a 10 linhas) respondendo: "Como o amor de Deus pode mudar a forma como eu vivo hoje?"',
    recompensa: "Amado por Deus",
    icone: "❤️",
    xp: 100,
  },
  3: {
    titulo: "O Pecado Entrou no Mundo",
    fase: "FASE 1: O Evangelho",
    objetivo: "Compreender que o pecado trouxe separação entre o homem e Deus, rompendo a comunhão original.",
    conteudo: [
      "O pecado não é apenas 'errar'; é romper o padrão e o propósito de Deus.",
      "Quando o pecado entrou no mundo, ele trouxe:",
      "• Distância espiritual",
      "• Vergonha",
      "• Culpa",
      "• Rejeição da presença de Deus",
      "O ser humano perdeu intimidade, direção e comunhão com Deus.",
      "",
      "Base bíblica:",
      "Romanos 3:23 — Todos pecaram e carecem da glória de Deus.",
      "Gênesis 3 — A queda da humanidade.",
      "Isaías 59:2 — O pecado faz separação entre nós e Deus.",
    ],
    versiculos: [
      {
        texto: "Porque todos pecaram e destituídos estão da glória de Deus.",
        referencia: "Romanos 3:23",
      },
      {
        texto:
          "Mas as vossas iniquidades fazem separação entre vós e o vosso Deus; e os vossos pecados encobrem o seu rosto de vós, para que não vos ouça.",
        referencia: "Isaías 59:2",
      },
    ],
    videos: [
      {
        id: "video-p3-1",
        titulo: "O que é pecado?",
        canal: "Física da Criação",
        duracao: "2:26",
        url: "https://www.youtube.com/watch?v=TMZg42grj7A",
      },
      {
        id: "video-p3-2",
        titulo: "A Doutrina do Pecado - Luiz Sayão",
        canal: "Com IBNU",
        duracao: "6:17",
        url: "https://www.youtube.com/watch?v=C5uz-Gogh04",
      },
      {
        id: "video-p3-3",
        titulo: "Por que Deus Permite o Mal? - Pr Rodrigo Silva",
        canal: "Gustavo Marques",
        duracao: "8:15",
        url: "https://www.youtube.com/watch?v=roFQbHGKpXA",
      },
    ],
    artigos: [
      {
        id: "artigo-p3-1",
        titulo: "O que é Pecado segunda a Bíblia",
        fonte: "Respostas Bíblicas do BibliaOn",
        url: "https://www.respostas.com.br/o-que-e-pecado/#:~:text=Pecado%20%C3%A9%EE%80%80%20n%C3%A3o%20estar%20em%20conformidade%20com%20o",
      },
      {
        id: "artigo-p3-2",
        titulo: "Queda do Homem",
        fonte: "Estilo Adoração",
        url: "https://estiloadoracao.com/a-queda-do-homem",
      },
      {
        id: "artigo-p3-3",
        titulo: "As consequências do pecado?",
        fonte: "Respostas Bíblicas do BibliaOn",
        url: "https://www.respostas.com.br/quais-sao-as-consequencias-do-pecado",
      },
    ],
    perguntaChave: "Por que o pecado causa separação entre o homem e Deus?",
    missao:
      "Identifique uma área da sua vida onde você precisa de mudança e explique por que. (Exemplos: relacionamentos, temperamento, vida espiritual, rotina/hábitos, pureza/pensamentos, obediência a Deus)",
    recompensa: "Reconhecimento da Verdade",
    icone: "👁️",
    xp: 100,
  },
  4: {
    titulo: "Consequências do Pecado",
    fase: "FASE 1: O Evangelho",
    objetivo: "Entender as quatro consequências devastadoras do pecado e por que o homem precisa de um Salvador.",
    conteudo: [
      "O pecado produz uma condição espiritual devastadora em toda a humanidade.",
      "Após a queda em Gênesis 3, surgiram quatro consequências universais:",
      "",
      "1️⃣ CULPA PERANTE A LEI DE DEUS",
      "Somos considerados culpados diante da justiça perfeita de Deus.",
      "Base bíblica:  Gênesis 3:23-24,  Romanos 1:18-21,  João 3:36,  Romanos 3:22-23",
      "",
      "",
      "2️⃣ MORTE ESPIRITUAL",
      "   A conexão espiritual com Deus foi rompida; o espírito humano se tornou inativo.",
      "   Base bíblica:  Efésios 2:1-3,  Ezequiel 18:4-9,  Jeremias 31:30",
      "",
      "",
      "3️⃣ INIMIZADE CONTRA DEUS",
      "   A natureza humana passa a resistir, ignorar e rejeitar Deus.",
      "   Base bíblica:   Gênesis 3:15,  Romanos 8:7,  Tiago 4:4,   Efésios 2:3",
      "",
      "",
      "4️⃣ ESCRAVIDÃO DO PECADO",
      "   O ser humano se torna dominado por seus desejos e pela inclinação para o mal.",
      "   Base bíblica:   Romanos 7:20-23,   Marcos 7:21-23,   Gálatas 5:19-21,   João 8:34",
      "",
      "",
      "Essas quatro áreas explicam por que o ser humano precisa de um Salvador.",
      "Por isso, o homem NÃO consegue se salvar sozinho.",
    ],
    versiculos: [
      {
        texto:
          "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.",
        referencia: "Romanos 6:23",
      },
      {
        texto: "Ele vos deu vida, estando vós mortos nos vossos delitos e pecados.",
        referencia: "Efésios 2:1",
      },
    ],
    videos: [
      {
        id: "video-p4-1",
        titulo: "O que o pecado faz conosco?",
        canal: "Pr. Osiel Gomes",
        duracao: "6:10",
        url: "https://www.youtube.com/watch?v=lZgv2AZKhQ0",
      },
      {
        id: "video-p4-2",
        titulo: "As consequências do pecado",
        canal: "Biblia Simples",
        duracao: "7:05",
        url: "https://www.youtube.com/watch?v=JDl8b_n3vf4&t=18s",
      },
      {
        id: "video-p4-3",
        titulo: "O salário do pecado é a morte - Romanos 6:23",
        canal: "Luz para o Caminho",
        duracao: "13:02",
        url: "https://www.youtube.com/watch?v=1HK9fmVpZno&t=1s",
      },
    ],
    artigos: [
      {
        id: "artigo-p4-1",
        titulo: "Culpa do Pecado: O Peso da Transgressão",
        fonte: "Got Questions",
        descricao:
          "Você sabia que a culpa do pecado não começa com você? Segundo a Bíblia, todos nascemos com uma 'culpa herdada' do pecado de Adão — chamada de pecado imputado. Isso significa que, antes mesmo de cometermos nosso primeiro erro, já somos considerados culpados diante de Deus! Mas não para por aí: cada escolha errada que fazemos adiciona nossa própria culpa pessoal. A boa notícia? Jesus Cristo oferece o único remédio: Sua justiça nos é creditada quando cremos Nele, apagando completamente nossa ficha criminal espiritual.",
        url: "https://www.gotquestions.org/Portugues/pecado-imputado.html",
      },
      {
        id: "artigo-p4-2",
        titulo: "Morte Espiritual: Vivo, mas Morto",
        fonte: "Voltemos ao Evangelho",
        descricao:
          "Imagine estar vivo fisicamente, mas completamente morto por dentro. Isso é a morte espiritual! Ela descreve o estado de todo ser humano antes de conhecer Cristo: insensível a Deus, mas hipersensível ao pecado. É como ter um órgão vital paralisado — você respira, come e dorme, mas está espiritualmente desconectado da fonte da vida. Paulo Washer explica que nascemos nesse estado devido ao julgamento que recaiu sobre Adão, e cada pecado que cometemos aprofunda ainda mais esse abismo. A única saída? O milagre da regeneração através de Cristo.",
        url: "https://voltemosaoevangelho.com/blog/2012/08/paul-washer-morte-espiritual-a-verdade-sobre-o-homem-410/",
      },
      {
        id: "artigo-p4-3",
        titulo: "Inimizade contra Deus: A Guerra Invisível",
        fonte: "Respostas Bíblicas",
        descricao:
          "A Bíblia afirma algo chocante: antes de Cristo, você e Deus eram inimigos! Tiago 4:4 diz que 'a amizade com o mundo é inimizade com Deus'. Mas aqui está o paradoxo: Deus nunca foi seu inimigo — você é quem se tornou inimigo Dele ao amar o pecado. Não existe terreno neutro: ou você é amigo de Deus (e inimigo do pecado), ou é amigo do pecado (e inimigo de Deus). Felizmente, Jesus veio destruir essa barreira de inimizade na cruz, oferecendo paz e reconciliação a todos que O aceitam.",
        url: "https://www.respostas.com.br/o-que-e-inimizade-na-biblia/",
      },
      {
        id: "artigo-p4-4",
        titulo: "Escravidão do Pecado: Acorrentado por Dentro",
        fonte: "Ultimato / John Stott",
        descricao:
          "Jesus foi direto ao ponto: 'Todo o que comete pecado é escravo do pecado' (João 8:34). Mas o que isso significa? A escravidão do pecado não é apenas fazer coisas erradas — é uma condição interior da qual você não consegue escapar sozinho. É como estar acorrentado em uma prisão invisível: você quer mudar, mas não consegue. Você promete parar, mas sempre volta. John Stott explica que os pecados visíveis são apenas sintomas de uma doença profunda no coração. A libertação? Romanos 6:18 promete: 'Libertados do pecado, vocês se tornaram servos da justiça' — mas isso só acontece através do poder de Cristo!",
        url: "https://ultimato.com.br/sites/john-stott/2014/08/25/escravidao-do-pecado",
      },
    ],
    leituraSemanal: {
      semana: 4,
      tema: "Jesus em ação - Parte 1",
      livro: "Marcos",
      capituloInicio: 1,
      capituloFim: 8,
      totalCapitulos: 8,
      descricao: "Acompanhe Jesus realizando milagres, ensinando com autoridade e revelando quem Ele é.",
    },
    perguntaChave: "Qual é o destino do ser humano sem reconciliação com Deus?",
    missao:
      'Escrever uma reflexão (3-5 linhas) respondendo: "O que eu acredito sobre a eternidade?" (Exemplos: Céu, Inferno, Vida após a morte, Comunhão eterna com Deus, Separação eterna)',
    recompensa: "Consciência Espiritual",
    icone: "🔥",
    xp: 100,
  },
  5: {
    titulo: "A Provisão Divina",
    fase: "FASE 1: O Evangelho",
    objetivo: "Compreender as quatro provisões que Jesus realizou na cruz, restaurando tudo que foi perdido no Éden.",
    conteudo: [
      "Cristo realizou quatro provisões fundamentais na cruz que restauram o relacionamento quebrado entre Deus e o homem:",
      "",
      "1️⃣ SUBSTITUIÇÃO",
      "Cristo tomou o nosso lugar na cruz.",
      "Base bíblica: 2 Coríntios 5:21, Isaías 53:6, Romanos 5:6-8, Colossenses 2:13-14",
      "Jesus assumiu a culpa que era nossa. Ele carregou o pecado e a condenação que deveriam recair sobre nós.",
      "",
      "2️⃣ RESSURREIÇÃO",
      "Cristo venceu a morte e abriu um novo caminho de vida.",
      "Base bíblica: Efésios 2:5, Romanos 6:4-14, 1 Pedro 3:20-21, 1 João 3:14",
      "A ressurreição é a prova de que Jesus é realmente Deus e de que a morte foi vencida. A nova vida no Espírito começa aqui.",
      "",
      "3️⃣ RECONCILIAÇÃO",
      "Cristo restaurou o relacionamento entre Deus e o homem.",
      "Base bíblica: Romanos 5:10-11, 2 Coríntios 5:17-19, Colossenses 1:21-22, Efésios 2:14-22",
      "Antes, éramos inimigos de Deus. Pela cruz, Jesus derrubou o muro de separação e fez paz entre nós e o Pai.",
      "",
      "4️⃣ REDENÇÃO",
      "Cristo pagou o preço para nos libertar.",
      "Base bíblica: Romanos 3:23-24, 1 Pedro 3:18, Hebreus 9:11-14, Colossenses 1:13-14",
      "Redenção significa 'comprar de volta'. Jesus pagou o preço do nosso pecado com Seu próprio sangue, libertando-nos da escravidão espiritual.",
    ],
    versiculos: [
      {
        texto: "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito...",
        referencia: "João 3:16",
      },
      {
        texto: "Àquele que não conheceu pecado, o fez pecado por nós...",
        referencia: "2 Coríntios 5:21",
      },
    ],
    videos: [
      {
        id: "video-p5-1",
        titulo: "Como Jesus promoveu uma substituição",
        canal: "Pr. Marcos Granconato",
        duracao: "3:14",
        url: "https://www.youtube.com/watch?v=LJYVRZ9VkXg",
      },
      {
        id: "video-p5-2",
        titulo: "Como morreu Jesus segundo a ciência?",
        canal: "BBC News Brasil",
        duracao: "6:43",
        url: "https://www.youtube.com/watch?v=lHANibG3krs&t=4s",
      },
      {
        id: "video-p5-3",
        titulo: "O que Jesus passou no Calvário? Pr. Rodrigo Silva",
        canal: "Cortes do Inteligência",
        duracao: "17:13",
        url: "https://www.youtube.com/watch?v=-KwsD31YX9s",
      },
    ],
    artigos: [
      {
        id: "artigo-p5-1",
        titulo: "O que é expiação substitutiva?",
        fonte: "Got Questions",
        descricao:
          "Jesus não apenas morreu por nós — Ele morreu EM NOSSO LUGAR! A substituição vicária significa que Cristo assumiu voluntariamente a punição que deveríamos receber. Imagine um juiz justo que condena um criminoso à morte, mas então desce do tribunal e morre no lugar dele. É exatamente isso que Jesus fez! 2 Coríntios 5:21 diz: 'Àquele que não conheceu pecado, Deus o fez pecado por nós'. Cristo trocou Sua justiça perfeita pela nossa culpa, para que pudéssemos ser justificados diante de Deus. Sem essa troca, não haveria salvação.",
        url: "https://www.gotquestions.org/Portugues/expiacao-substituta.html",
      },
      {
        id: "artigo-p5-2",
        titulo: "O Evangelho da Ressurreição de Jesus: A Vitória sobre a Morte",
        fonte: "Oitava Igreja Presbiteriana de BH",
        descricao:
          "A ressurreição não é apenas um 'final feliz' — é a PROVA DEFINITIVA de que Jesus é quem Ele diz ser! Se Cristo não ressuscitou, nossa fé é inútil (1 Coríntios 15:14). Mas Ele ressuscitou! E isso muda TUDO. A ressurreição garante que o poder do pecado e da morte foi quebrado. Efésios 2:5 declara que Deus 'nos deu vida juntamente com Cristo'. Não é apenas sobre ir para o céu um dia — é sobre viver uma NOVA VIDA agora, cheia do poder do Espírito Santo que ressuscitou Jesus dos mortos!",
        url: "https://www.oitavaigreja.org.br/artigo/o-evangelho-da-ressurreicao-nos-da-vitoria-sobre-a-morte",
      },
      {
        id: "artigo-p5-3",
        titulo: "Reconciliação: De Inimigos a Filhos",
        fonte: "Got Questions",
        descricao:
          "Reconciliação significa restaurar um relacionamento quebrado. E nosso relacionamento com Deus estava DEVASTADO pelo pecado. Romanos 5:10 diz que 'éramos inimigos' de Deus! Mas através da cruz, Jesus demoliu o muro de separação. Colossenses 1:21-22 proclama: 'Vocês, que antes eram estranhos e inimigos... agora foram reconciliados pelo corpo físico de Cristo'. Não somos mais escravos fugitivos — somos FILHOS adotados! A reconciliação nos dá acesso total à presença de Deus, não por nosso mérito, mas pelo sangue de Cristo.",
        url: "https://www.gotquestions.org/Portugues/reconciliacao-Crista.html",
      },
      {
        id: "artigo-p5-4",
        titulo: "Redenção: Comprados com Sangue",
        fonte: "Got Questions",
        descricao:
          "Redenção vem de uma palavra que significa 'comprar de volta' — como pagar um resgate para libertar um escravo. E é exatamente isso que Jesus fez! Colossenses 1:13-14 declara: 'Ele nos libertou do domínio das trevas e nos transportou para o Reino do Filho amado, em quem temos a redenção, a saber, o perdão dos pecados'. O preço? O precioso sangue de Cristo (1 Pedro 1:18-19). Não fomos redimidos com ouro ou prata, mas com a própria vida de Jesus. Que amor incomparável!",
        url: "https://www.gotquestions.org/Portugues/redencao-Crista.html",
      },
    ],
    leituraSemanal: {
      semana: 5,
      tema: "Jesus em ação - Parte 2",
      livro: "Marcos",
      capituloInicio: 9,
      capituloFim: 16,
      totalCapitulos: 8,
      descricao: "Acompanhe a jornada de Jesus até a cruz, Sua morte, ressurreição e a comissão final aos discípulos.",
    },
    perguntaChave: "Qual é o significado da cruz para você?",
    missao:
      "Ler João 3 (todo o capítulo) e enviar ao discipulador uma parte que chamou atenção e o porquê. (3-5 linhas com aplicação pessoal)",
    recompensa: "Cristo é o Caminho",
    icone: "✝️",
    xp: 100,
  },
  6: {
    titulo: "A Morte e Ressurreição de Cristo",
    fase: "FASE 1: O Evangelho",
    objetivo: "Cristo venceu o pecado e a morte através do Seu sacrifício e ressurreição.",
    conteudo: [
      "A morte de Jesus não foi um acidente, mas o cumprimento do plano divino de salvação.",
      "Isaías 53 profetizou o Servo Sofredor que levaria sobre si os pecados da humanidade.",
      "Jesus morreu voluntariamente como substituto perfeito, pagando a dívida que não podíamos pagar.",
      "A ressurreição ao terceiro dia provou que Jesus é quem dizia ser.",
      "Romanos 4:25 declara que Ele foi entregue por nossas transgressões e ressuscitou para nossa justificação.",
      "A ressurreição é a garantia da nossa própria ressurreição futura.",
    ],
    versiculos: [
      {
        texto:
          "Cristo morreu pelos nossos pecados, segundo as Escrituras, foi sepultado e ressuscitou ao terceiro dia.",
        referencia: "1 Coríntios 15:3-4",
      },
    ],
    videos: [
      {
        id: "video-1",
        titulo: "A Ressurreição de Jesus",
        canal: "Hermeson César",
        duracao: "6:26",
        url: "https://www.youtube.com/watch?v=KHQQazCbV-0",
      },
      {
        id: "video-2",
        titulo: "Por que Jesus morreu pelos nosso pecados? - Augustus Nicodemus",
        canal: "Cortes do Inteligência",
        duracao: "11:17",
        url: "https://www.youtube.com/watch?v=2CsL4E5o7JM",
      },
      {
        id: "video-3",
        titulo: "A ressurreição na volta de Jesus com Rodrigo Silva",
        canal: "A Bíblia Comentada",
        duracao: "8:18",
        url: "https://www.youtube.com/watch?v=rgSZBv1LfU0",
      },
    ],
    artigos: [
      {
        id: "artigo-1",
        titulo: "A Morte de Jesus Cristo",
        fonte: "Wikipedia",
        url: "https://pt.wikipedia.org/wiki/Morte_de_Jesus",
      },
      {
        id: "artigo-2",
        titulo: "A Ressurreição: Prova e Poder",
        fonte: "Wikipedia",
        url: "https://pt.wikipedia.org/wiki/Ressurrei%C3%A7%C3%A3o_de_Jesus",
      },
      {
        id: "artigo-3",
        titulo: "Expiação e Justificação",
        fonte: "Wikipedia",
        url: "https://pt.wikipedia.org/wiki/Expia%C3%A7%C3%A3o",
      },
    ],
    leituraSemanal: {
      semana: 6,
      tema: "Lucas: O Filho do Homem",
      livro: "Lucas",
      capituloInicio: 1,
      capituloFim: 8,
      totalCapitulos: 8,
      descricao:
        "Conheça Jesus como o Filho do Homem que veio buscar e salvar o perdido, apresentado por Lucas com detalhes históricos e compaixão.",
    },
    perguntaChave: "O que muda na vida de uma pessoa porque Jesus ressuscitou?",
    missao:
      "Assistir a uma pregação ou estudo sobre a ressurreição e enviar ao discipulador um resumo de 5 a 8 linhas sobre o que mais impactou.",
    recompensa: "Nova Vida",
    icone: "⚰️",
    xp: 100,
  },
}

export type PassoNumero = keyof typeof PASSOS_CONTEUDO
