export const PASSOS_CONTEUDO = {
  1: {
    titulo: "Deus nos Criou",
    fase: "FASE 1: O Evangelho",
    objetivo: "Entender que a vida não é um acidente: fomos criados por Deus com propósito.",
    conteudo: [
      "Deus é o Criador de todas as coisas.",
      "Ele nos fez à Sua imagem (Gênesis 1:26–27).",
      "Isso significa que:",
      "• Temos valor",
      "• Temos identidade",
      "• Fomos criados para nos relacionar com Ele",
      "Você não é um acaso.",
      "Você existe porque Deus desejou a sua vida.",
    ],
    versiculos: [{ texto: "No princípio, criou Deus os céus e a terra.", referencia: "Gênesis 1:1" }],
    videos: [
      {
        id: "video-1",
        titulo: "O que significa ser criado à imagem de Deus?",
        canal: "Cristãos na Ciência",
        duracao: "9:33",
        url: "https://www.youtube.com/watch?v=rr6k9AVyO1Y",
      },
      {
        id: "video-2",
        titulo: "Gênesis 1 - A Criação",
        canal: "Israel da Costa Homem",
        duracao: "7:14",
        url: "https://www.youtube.com/watch?v=uwjM5q6H3Vo&list=RDuwjM5q6H3Vo&start_radio=1",
      },
      {
        id: "video-3",
        titulo: "Por que Deus nos Criou?",
        canal: "Primo Cast",
        duracao: "6:29",
        url: "https://www.youtube.com/watch?v=476WjoLrND0",
      },
    ],
    artigos: [
      {
        id: "artigo-1",
        titulo: "Imago Dei (Imagem de Deus)",
        fonte: "Teólogo Internacional",
        url: "https://teologointernacional.com.br/o-que-significa-ser-criado-a-imagem-e-semelhanca-de-deus-estudos-biblicos/",
      },
      {
        id: "artigo-2",
        titulo: "Fomos Criados para Relacionamento",
        fonte: "fhopchurch",
        url: "https://fhop.com/criados-para-relacionamento/",
      },
      {
        id: "artigo-3",
        titulo: "Criação (Cristianismo)",
        fonte: "Bibliaon",
        url: "https://www.bibliaon.com/os_dias_da_criacao/",
      },
    ],
    perguntaChave: "Qual o propósito da criação do ser humano?",
    missao: 'Escreva uma frase respondendo: "Por que eu existo?"',
    recompensa: "Identidade dada por Deus",
    icone: "✨",
    xp: 100,
  },
  2: {
    titulo: "Deus nos Ama",
    fase: "FASE 1: O Evangelho",
    objetivo: "Reconhecer que o amor de Deus é a base do discipulado e o fundamento de todo relacionamento com Ele.",
    conteudo: [
      "Deus não apenas nos criou, mas nos ama profundamente.",
      "Esse amor é constante, imutável e demonstrado através de suas ações na história.",
      "O maior ato desse amor foi enviar Seu Filho Jesus Cristo para restaurar nossa relação com Ele.",
      "Base bíblica:",
      '• João 3:16 — "Porque Deus amou o mundo de tal maneira…"',
      '• Romanos 5:8 — "Mas Deus prova o seu amor para conosco…"',
      '• 1 João 4:7–10 — "Deus é amor."',
      "O discipulado não começa com medo, pressão ou religião, mas com amor.",
    ],
    versiculos: [
      {
        texto:
          "Porque Deus amou o mundo de tal maneira que deu o seu Filho unigênito, para que todo aquele que nele crê não pereça, mas tenha a vida eterna.",
        referencia: "João 3:16",
      },
    ],
    videos: [
      {
        id: "video-p2-1",
        titulo: "Deus te ama – resumo bíblico",
        canal: "Primo Cast",
        duracao: "0:40",
        url: "https://www.youtube.com/watch?v=UxkmVtpk2m0",
      },
      {
        id: "video-p2-2",
        titulo: "O que é o amor de Deus? (Explicação simples)",
        canal: "Luciano Subirá",
        duracao: "11:53",
        url: "https://www.youtube.com/watch?v=eER6r_Qyq1Y",
      },
      {
        id: "video-p2-3",
        titulo: "O Maravilho Amor de Deus",
        canal: "Desenhando a Bíblia",
        duracao: "4:45",
        url: "https://www.youtube.com/watch?v=VO5YhS9ErDc",
      },
    ],
    artigos: [
      {
        id: "artigo-p2-1",
        titulo: "Amor de Deus (Cristianismo)",
        fonte: "PADD",
        url: "https://peloamordedeus.org.br/o-amor-cristao/",
      },
      {
        id: "artigo-p2-2",
        titulo: "João 3:16 – contexto",
        fonte: "O pregador",
        url: "https://opregador.com/esboco-de-pregacao-sobre-joao-316/",
      },
      {
        id: "artigo-p2-3",
        titulo: "Natureza de Deus – Deus é Amor",
        fonte: "Sobre Pregação",
        url: "https://sobrepregacao.com/2024/03/pregacao-sobre-joao-316-porque-deus-amou-o-mundo-de-tal-maneira-que/",
      },
    ],
    perguntaChave: "Como você descreveria o amor de Deus por você, de forma pessoal?",
    missao:
      'Escrever uma pequena carta (5 a 10 linhas) respondendo: "Como o amor de Deus pode mudar a forma como eu vivo hoje?"',
    recompensa: "Amado por Deus",
    icone: "❤️",
    xp: 100,
  },
  3: {
    titulo: "O Pecado Entrou no Mundo",
    fase: "FASE 1: O Evangelho",
    objetivo: "Compreender que o pecado trouxe separação entre o homem e Deus, rompendo a comunhão original.",
    conteudo: [
      "O pecado não é apenas 'errar'; é romper o padrão e o propósito de Deus.",
      "Quando o pecado entrou no mundo, ele trouxe:",
      "• Distância espiritual",
      "• Vergonha",
      "• Culpa",
      "• Rejeição da presença de Deus",
      "O ser humano perdeu intimidade, direção e comunhão com Deus.",
      "Base bíblica:",
      '• Romanos 3:23 — "Todos pecaram e carecem da glória de Deus."',
      "• Gênesis 3 — A queda da humanidade.",
      '• Isaías 59:2 — "O pecado faz separação entre nós e Deus."',
    ],
    versiculos: [
      {
        texto: "Porque todos pecaram e destituídos estão da glória de Deus.",
        referencia: "Romanos 3:23",
      },
      {
        texto:
          "Mas as vossas iniquidades fazem separação entre vós e o vosso Deus; e os vossos pecados encobrem o seu rosto de vós, para que não vos ouça.",
        referencia: "Isaías 59:2",
      },
    ],
    videos: [
      {
        id: "video-p3-1",
        titulo: "O que é pecado?",
        canal: "Física da Criação",
        duracao: "2:26",
        url: "https://www.youtube.com/watch?v=TMZg42grj7A",
      },
      {
        id: "video-p3-2",
        titulo: "A Doutrina do Pecado - Luiz Sayão",
        canal: "Com IBNU",
        duracao: "6:17",
        url: "https://www.youtube.com/watch?v=C5uz-Gogh04",
      },
      {
        id: "video-p3-3",
        titulo: "Por que Deus Permite o Mal? - Pr Rodrigo Silva",
        canal: "Gustavo Marques",
        duracao: "8:15",
        url: "https://www.youtube.com/watch?v=roFQbHGKpXA",
      },
    ],
    artigos: [
      {
        id: "artigo-p3-1",
        titulo: "O que é Pecado segunda a Bíblia",
        fonte: "Respostas Bíblicas do BibliaOn",
        url: "https://www.respostas.com.br/o-que-e-pecado/#:~:text=Pecado%20%C3%A9%EE%80%80%20n%C3%A3o%20estar%20em%20conformidade%20com%20o",
      },
      {
        id: "artigo-p3-2",
        titulo: "Queda do Homem",
        fonte: "Estilo Adoração",
        url: "https://estiloadoracao.com/a-queda-do-homem",
      },
      {
        id: "artigo-p3-3",
        titulo: "As consequências do pecado?",
        fonte: "Respostas Bíblicas do BibliaOn",
        url: "https://www.respostas.com.br/quais-sao-as-consequencias-do-pecado",
      },
    ],
    perguntaChave: "Por que o pecado causa separação entre o homem e Deus?",
    missao:
      "Identifique uma área da sua vida onde você precisa de mudança e explique por que. (Exemplos: relacionamentos, temperamento, vida espiritual, rotina/hábitos, pureza/pensamentos, obediência a Deus)",
    recompensa: "Reconhecimento da Verdade",
    icone: "👁️",
    xp: 100,
  },
  4: {
    titulo: "Consequências do Pecado",
    fase: "FASE 1: O Evangelho",
    objetivo: "Entender as quatro consequências devastadoras do pecado e por que o homem precisa de um Salvador.",
    conteudo: [
      "O pecado produz uma condição espiritual devastadora em toda a humanidade.",
      "Após a queda em Gênesis 3, surgiram quatro consequências universais:",
      "",
      "1️⃣ CULPA PERANTE A LEI DE DEUS",
      "• Gênesis 3:23-24; Romanos 1:18-21; João 3:36; Romanos 3:22-23",
      "• Somos considerados culpados diante da justiça perfeita de Deus.",
      "",
      "2️⃣ MORTE ESPIRITUAL",
      "• Efésios 2:1-3; Ezequiel 18:4-9; Jeremias 31:30",
      "• A conexão espiritual com Deus foi rompida; o espírito humano se tornou inativo.",
      "",
      "3️⃣ INIMIZADE CONTRA DEUS",
      "• Gênesis 3:15; Romanos 8:7; Tiago 4:4; Efésios 2:3",
      "• A natureza humana passa a resistir, ignorar e rejeitar Deus.",
      "",
      "4️⃣ ESCRAVIDÃO DO PECADO",
      "• Romanos 7:20-23; Marcos 7:21-23; Gálatas 5:19-21; João 8:34,36",
      "• O ser humano se torna dominado por seus desejos e pela inclinação para o mal.",
      "",
      "Essas quatro áreas explicam por que o ser humano precisa de um Salvador.",
      "Por isso, o homem NÃO consegue se salvar sozinho.",
    ],
    versiculos: [
      {
        texto:
          "Porque o salário do pecado é a morte, mas o dom gratuito de Deus é a vida eterna em Cristo Jesus, nosso Senhor.",
        referencia: "Romanos 6:23",
      },
      {
        texto: "Ele vos deu vida, estando vós mortos nos vossos delitos e pecados.",
        referencia: "Efésios 2:1",
      },
    ],
    videos: [
      {
        id: "video-p4-1",
        titulo: "O que o pecado faz conosco?",
        canal: "Douglas Gonçalves",
        duracao: "3:00",
        url: "https://www.youtube.com/watch?v=2hHKLx7nImE",
      },
      {
        id: "video-p4-2",
        titulo: "As consequências do pecado",
        canal: "BibleProject",
        duracao: "5:18",
        url: "https://www.youtube.com/watch?v=xMVXo_9wTdc",
      },
    ],
    artigos: [
      {
        id: "artigo-p4-1",
        titulo: "Pecado (Cristianismo)",
        fonte: "Wikipédia",
        url: "https://pt.wikipedia.org/wiki/Pecado",
      },
      {
        id: "artigo-p4-2",
        titulo: "Morte Espiritual - Estudo",
        fonte: "Wikipédia",
        url: "https://pt.wikipedia.org/wiki/Morte_espiritual",
      },
      {
        id: "artigo-p4-3",
        titulo: "As Consequências do Pecado",
        fonte: "Respostas Bíblicas",
        url: "https://www.respostas.com.br/quais-sao-as-consequencias-do-pecado",
      },
    ],
    perguntaChave: "Qual é o destino do ser humano sem reconciliação com Deus?",
    missao:
      'Escrever uma reflexão (3-5 linhas) respondendo: "O que eu acredito sobre a eternidade?" (Exemplos: Céu, Inferno, Vida após a morte, Comunhão eterna com Deus, Separação eterna)',
    recompensa: "Consciência Espiritual",
    icone: "🔥",
    xp: 100,
  },
}

export type PassoNumero = keyof typeof PASSOS_CONTEUDO
