export const PERGUNTAS_POR_PASSO: Record<number, string[]> = {
  1: [
    "Ao refletir sobre os sete dias da criação, onde Deus ordenou o caos e trouxe beleza e propósito a cada elemento, como isso transforma sua visão sobre o mundo ao seu redor? De que maneiras você pode celebrar e cuidar melhor da criação de Deus como um mordomo responsável?",
    "Se você foi criado à imagem e semelhança de Deus com capacidades únicas de raciocínio, amor, criatividade e relacionamento, como essa verdade deve moldar sua identidade e seu valor próprio? Em quais áreas de sua vida você precisa permitir que Cristo restaure a imagem divina que foi distorcida pelo pecado?",
    "Deus desejou relacionamento desde o Éden e continua buscando comunhão íntima conosco. Como está sua resposta a esse convite divino? De que formas você pode investir mais profundamente em seu relacionamento com Deus e também cultivar relacionamentos genuínos e transformadores com outras pessoas?",
  ],
  2: [
    "Como você pode compreender e experimentar pessoalmente a profundidade do amor de Deus revelado no sacrifício de Jesus Cristo? De que maneiras específicas esse amor transformou ou pode transformar sua vida e relacionamentos?",
    "Sabendo que a salvação não pode ser merecida por obras, mas é um presente gratuito de Deus, como isso afeta sua compreensão da graça divina? Como você pode viver em gratidão diária por esse dom inestimável e compartilhá-lo com outros?",
    "A oferta de salvação é universal e inclusiva, estendida a todas as pessoas sem discriminação. Como essa verdade pode influenciar sua maneira de enxergar e tratar as pessoas ao seu redor? Que barreiras (culturais, sociais, pessoais) você precisa derrubar para refletir esse amor inclusivo de Deus?",
  ],
  3: [
    "Como você entende a diferença entre 'estar em estado de pecado' e 'cometer atos pecaminosos'? De que forma essa compreensão muda sua visão sobre santidade e dependência de Deus?",
    "Refletindo sobre a Queda de Adão e Eva, como você identifica o mesmo padrão de tentação (duvidar da Palavra de Deus → desacreditar → autossuficiência → desobediência) em sua própria vida? Que áreas você precisa entregar a Deus?",
    "Quais consequências do pecado você já experimentou pessoalmente? Como o conhecimento do amor e perdão de Deus através de Cristo transforma sua resposta ao pecado?",
  ],
  4: [
    "Você compreende que nasceu com uma 'culpa herdada' do pecado de Adão (pecado imputado), além da culpa pessoal por seus próprios erros? Como essa verdade impacta sua percepção da necessidade de um Salvador e da graça de Cristo que apaga completamente sua 'ficha criminal espiritual'?",
    "Paulo Washer afirma que a morte espiritual significa estar 'vivo fisicamente, mas completamente morto por dentro' — insensível a Deus, mas hipersensível ao pecado. Você já experimentou essa realidade em sua vida? Como o milagre da regeneração através de Cristo transforma esse estado de morte espiritual em vida abundante?",
    "Tiago 4:4 diz que 'a amizade com o mundo é inimizade com Deus'. Antes de conhecer Cristo, você reconhece que era inimigo de Deus ao amar o pecado? Como Jesus destruiu essa barreira de inimizade na cruz e ofereceu paz e reconciliação? De que formas práticas você demonstra hoje que é amigo de Deus e não do pecado?",
    "Jesus declarou: 'Todo o que comete pecado é escravo do pecado' (João 8:34). Você já se sentiu acorrentado em uma prisão invisível, querendo mudar mas não conseguindo? Quais áreas específicas de sua vida ainda lutam contra essa escravidão? Como Romanos 6:18 ('Libertados do pecado, vocês se tornaram servos da justiça') se aplica à sua jornada de libertação através do poder de Cristo?",
  ],
  5: [
    "Como você compreende a substituição vicária de Cristo na cruz? De que maneiras específicas você tem experimentado a liberdade de saber que Jesus tomou o SEU lugar, carregando a punição que você merecia? Em quais áreas da sua vida você ainda carrega culpa desnecessária, mesmo sabendo que Cristo já pagou completamente por seus pecados?",
    "A ressurreição de Jesus não é apenas sobre Ele vencer a morte — é sobre VOCÊ receber nova vida! Romanos 6:4 diz que 'fomos sepultados com ele na morte, para que, assim como Cristo foi ressuscitado... também nós vivamos uma vida nova'. Quais sinais de 'vida nova' você tem visto em sua jornada? Que áreas da sua vida ainda parecem 'mortas' e precisam do poder da ressurreição de Cristo?",
    "Reconciliação com Deus significa que a guerra acabou — você não é mais inimigo, mas filho amado! Como essa verdade transforma sua maneira de se relacionar com Deus? Você ainda se aproxima Dele com medo e insegurança, ou com confiança de filho reconciliado? De que formas práticas você pode viver essa paz conquistada na cruz em seus relacionamentos diários?",
    "Redenção significa que você foi 'comprado de volta' — você não pertence mais ao pecado, mas a Cristo! 1 Coríntios 6:19-20 declara: 'Vocês não são de si mesmos; foram comprados por alto preço'. Como essa verdade impacta suas escolhas diárias? Em quais áreas da sua vida você precisa lembrar que foi redimido e agora pertence completamente a Jesus? Como você pode honrar esse 'alto preço' que Cristo pagou?",
  ],
  6: [
    "A morte de Jesus não foi um acidente trágico, mas o cumprimento do plano perfeito de Deus para sua salvação. Como essa verdade muda sua perspectiva sobre o sofrimento e o sacrifício? De que maneiras você pode valorizar mais profundamente o preço que Cristo pagou por você na cruz? Que sacrifícios Deus está pedindo de você hoje como resposta ao sacrifício de Jesus?",
    "1 Coríntios 15:14 declara: 'Se Cristo não ressuscitou, é vã a nossa pregação, e vã também a vossa fé'. A ressurreição é a prova definitiva de que Jesus é Deus e de que Ele venceu a morte. Como essa certeza fortalece sua fé nos momentos de dúvida? O que muda na sua vida sabendo que o mesmo poder que ressuscitou Jesus dos mortos está disponível para você hoje?",
    "A morte de Cristo nos traz perdão, e a ressurreição nos dá vida nova e esperança eterna. Romanos 6:4 nos convida a 'viver uma vida nova' pelo poder da ressurreição. Que áreas da sua vida refletem essa 'vida nova' em Cristo? Quais hábitos, pensamentos ou relacionamentos ainda precisam experimentar o poder transformador da ressurreição? Como você pode morrer para o velho homem e ressuscitar para uma nova maneira de viver?",
  ],
  7: [
    "Conversão não é apenas 'virar crente', mas uma transformação radical do coração. Lucas 15 mostra o filho pródigo 'caindo em si' e voltando para o pai. Você já experimentou esse momento de 'cair em si' em relação à sua necessidade de Deus? Quais sinais de verdadeira conversão você vê em sua vida hoje? Em quais áreas você ainda precisa 'voltar para o Pai'?",
    "Regeneração significa nascer de novo - não é reforma, é RENASCIMENTO! João 3:7 declara: 'Importa-vos nascer de novo'. Você consegue identificar evidências de 'nova vida' espiritual em você desde que conheceu Cristo? Que diferenças práticas esse novo nascimento trouxe para seus pensamentos, relacionamentos e prioridades?",
    "Como embaixadores de Cristo (2 Coríntios 5:20), representamos oficialmente o Reino de Deus no mundo. Como você tem cumprido essa missão no seu ambiente de trabalho, família e círculo social? Que barreiras (medo, vergonha, comodismo) impedem você de ser um embaixador mais fiel? Como pode superá-las?",
    "Propiciação significa que Jesus satisfez completamente a ira de Deus contra o pecado. Romanos 3:25 diz que Deus apresentou Cristo como 'propiciação pelo seu sangue'. Como entender que a justiça de Deus foi plenamente satisfeita muda sua percepção sobre segurança eterna? Você vive com medo de que Deus ainda esteja irado com você, ou descansa na certeza de que Cristo já pagou TUDO?",
  ],
  8: [
    "Jesus demonstrou compaixão radical pelos marginalizados — leprosos, cobradores de impostos, prostitutas, pecadores desprezados. O sermão sobre Compaixão pelos Perdidos mostra que compaixão é sentir a dor do outro e AGIR para ajudar, não apenas ter pena. Mateus 9:36 diz que Jesus 'teve compaixão da multidão porque estavam cansadas e aflitas como ovelhas sem pastor'. Como a compaixão de Jesus por VOCÊ (quando você estava perdido e sem direção) deve transformar a maneira como você enxerga e trata os 'perdidos' ao seu redor? Quem são as pessoas 'cansadas e aflitas' em sua vida que precisam experimentar a compaixão ativa de Cristo através de você esta semana?",
    "A parábola do filho pródigo (Lucas 15:11-32) mostra dois filhos perdidos: um longe de casa gastando sua herança com prostitutas, e outro dentro de casa cheio de amargura e ciúme. Mas o protagonista é o PAI AMOROSO que corre ao encontro do filho que volta arrependido E vai buscar o filho mais velho que não quer entrar na festa. O material da Igreja Presbiteriana enfatiza: 'Os braços do pai são acolhimento e refúgio para os ausentes que voltam, mas também são reconciliação e ternura para os presentes que se chateiam'. Você se identifica mais com qual filho? Como Deus tem demonstrado Seu amor de Pai para você — esperando pacientemente, correndo para abraçar, ou indo buscar você quando está distante?",
    "Lucas 19:10 declara a missão de Jesus: 'O Filho do Homem veio buscar e salvar o que estava perdido'. O Evangelho de Lucas é marcado pela misericórdia — Jesus tocou leprosos (considerados imundos), foi à casa de Zaqueu (cobrador de impostos corrupto), defendeu a mulher pecadora, e comeu com publicanos e pecadores. Lucas 6:36 nos ordena: 'Sede misericordiosos como vosso Pai é misericordioso'. Como você tem seguido o exemplo de Jesus de buscar ATIVAMENTE os perdidos e marginalizados? Que barreiras sociais, culturais ou pessoais você precisa quebrar para demonstrar a compaixão de Cristo a alguém quebrantado, rejeitado ou necessitado em sua comunidade esta semana?",
  ],
  9: [
    "Romanos 10:9 une dois elementos inseparáveis: 'crer no coração' que Deus ressuscitou Jesus e 'confessar com a boca' que Jesus é Senhor. Paulo explica que o coração crê para justiça e a boca confessa para salvação. Você tem dificuldade de confessar publicamente sua fé em Jesus? Em quais ambientes (trabalho, escola, família, redes sociais) você esconde ou minimiza sua identidade cristã? Como seria confessar corajosamente o senhorio de Cristo esta semana, sabendo que Mateus 10:32 promete que Jesus também o confessará diante do Pai?",
    "O material sobre Senhorio de Cristo mostra que após a conversão há uma decisão determinante: entregar-se completamente em rendição total ou viver segundo suas próprias vontades. Filipenses 3:7-11 revela Paulo considerando tudo como 'lixo' para ganhar Cristo. Quais áreas da sua vida você ainda mantém sob SEU controle ao invés de submeter ao senhorio de Jesus? (Exemplos: carreira, relacionamentos amorosos, finanças, uso do tempo livre, decisões importantes, entretenimento). O que especificamente impede você de entregar totalmente essas áreas a Cristo? Que mudanças concretas você precisa fazer esta semana para demonstrar submissão prática ao Senhor?",
    "Lucas 9:23 estabelece a condição para seguir Jesus: 'Negue-se a si mesmo, tome sua cruz e siga-me'. Negar a si mesmo significa destronizar o 'eu' para que Cristo reine — não é perda de identidade, mas descoberta do verdadeiro propósito! O material explica que quanto maior a tolerância com as vontades da carne, maior o afastamento de Cristo e a escravidão do pecado. Em quais situações práticas você precisa 'negar a si mesmo' diariamente? Como seria sua vida se você realmente colocasse os interesses de Cristo acima dos seus próprios desejos, planos e conforto? Você está disposto a 'morrer para o eu' para viver plenamente para Cristo?",
  ],
  10: [
    "João 3:3 declara: 'Se alguém não nascer de novo, não pode ver o Reino de Deus'. O novo nascimento é uma transformação COMPLETA operada pelo Espírito Santo, não uma reforma moral. John Piper explica que a regeneração nos dá novos desejos, nova natureza e nova capacidade de ver e amar Cristo. Você consegue identificar evidências concretas de 'nova criação' em você? Que mudanças práticas o Espírito Santo produziu em seus pensamentos, desejos e relacionamentos desde sua conversão? Se não há transformação visível, o que isso revela sobre sua condição espiritual?",
    "Romanos 8:1 declara: 'Nenhuma condenação há para os que estão em Cristo Jesus'. R.C. Sproul ensina que a justificação não é progressiva, mas instantânea — na cruz houve uma GRANDE TROCA: Cristo levou sua culpa e creditou Sua justiça perfeita a você! Você vive na liberdade gloriosa de quem foi justificado, ou ainda carrega peso de condenação? Quais pecados do passado ainda fazem você duvidar do perdão completo de Deus? Como seria sua vida se você descansasse plenamente na verdade de que está PERFEITAMENTE aceito pelo Pai em Cristo?",
    "Gálatas 4:5-7 proclama que fomos 'adotados como filhos' — você não é escravo medroso nem estranho distante, mas FILHO AMADO com acesso total ao Pai! Paul Washer enfatiza que a adoção é permanente, irrevogável e nos dá identidade nova, herança garantida e relacionamento íntimo. Você realmente vive com essa identidade de filho adotado, ou ainda se relaciona com Deus com medo e insegurança? Como seria sua oração, culto e obediência se você abraçasse plenamente sua identidade como co-herdeiro com Cristo e membro permanente da família de Deus?",
    "Filipenses 3:20-21 promete que Cristo 'transformará nosso corpo de humilhação para ser igual ao corpo da sua glória'. Augustus Nicodemus explica que a glorificação é a etapa final da salvação — receberemos corpos RESSURRETOS, IMORTAIS e INCORRUPTÍVEIS como o de Cristo! Romanos 8:23 revela que aguardamos 'a redenção do nosso corpo'. Como essa esperança gloriosa de transformação corporal futura impacta a maneira como você vive hoje? De que formas você pode honrar seu corpo agora sabendo que ele será glorificado eternamente? Como essa certeza de ressurreição o fortalece diante do sofrimento, da dor e da morte?",
  ],
}

// Mantendo compatibilidade com código existente
export const perguntasPorPasso = PERGUNTAS_POR_PASSO

export function getPerguntasPasso(numero: number): string[] {
  return PERGUNTAS_POR_PASSO[numero] || []
}
