-- Popular tabela de livros da Bíblia (Antigo Testamento)
INSERT INTO livros_biblia (abreviacao, nome, testamento, ordem, total_capitulos) VALUES
('gn', 'Gênesis', 'Antigo', 1, 50),
('ex', 'Êxodo', 'Antigo', 2, 40),
('lv', 'Levítico', 'Antigo', 3, 27),
('nm', 'Números', 'Antigo', 4, 36),
('dt', 'Deuteronômio', 'Antigo', 5, 34),
('js', 'Josué', 'Antigo', 6, 24),
('jz', 'Juízes', 'Antigo', 7, 21),
('rt', 'Rute', 'Antigo', 8, 4),
('1sm', '1 Samuel', 'Antigo', 9, 31),
('2sm', '2 Samuel', 'Antigo', 10, 24),
('1rs', '1 Reis', 'Antigo', 11, 22),
('2rs', '2 Reis', 'Antigo', 12, 25),
('1cr', '1 Crônicas', 'Antigo', 13, 29),
('2cr', '2 Crônicas', 'Antigo', 14, 36),
('ed', 'Esdras', 'Antigo', 15, 10),
('ne', 'Neemias', 'Antigo', 16, 13),
('et', 'Ester', 'Antigo', 17, 10),
('jó', 'Jó', 'Antigo', 18, 42),
('sl', 'Salmos', 'Antigo', 19, 150),
('pv', 'Provérbios', 'Antigo', 20, 31),
('ec', 'Eclesiastes', 'Antigo', 21, 12),
('ct', 'Cântico dos Cânticos', 'Antigo', 22, 8),
('is', 'Isaías', 'Antigo', 23, 66),
('jr', 'Jeremias', 'Antigo', 24, 52),
('lm', 'Lamentações', 'Antigo', 25, 5),
('ez', 'Ezequiel', 'Antigo', 26, 48),
('dn', 'Daniel', 'Antigo', 27, 12),
('os', 'Oséias', 'Antigo', 28, 14),
('jl', 'Joel', 'Antigo', 29, 3),
('am', 'Amós', 'Antigo', 30, 9),
('ob', 'Obadias', 'Antigo', 31, 1),
('jn', 'Jonas', 'Antigo', 32, 4),
('mq', 'Miquéias', 'Antigo', 33, 7),
('na', 'Naum', 'Antigo', 34, 3),
('hc', 'Habacuque', 'Antigo', 35, 3),
('sf', 'Sofonias', 'Antigo', 36, 3),
('ag', 'Ageu', 'Antigo', 37, 2),
('zc', 'Zacarias', 'Antigo', 38, 14),
('ml', 'Malaquias', 'Antigo', 39, 4);

-- Popular tabela de livros da Bíblia (Novo Testamento)
INSERT INTO livros_biblia (abreviacao, nome, testamento, ordem, total_capitulos) VALUES
('mt', 'Mateus', 'Novo', 40, 28),
('mc', 'Marcos', 'Novo', 41, 16),
('lc', 'Lucas', 'Novo', 42, 24),
('jo', 'João', 'Novo', 43, 21),
('at', 'Atos', 'Novo', 44, 28),
('rm', 'Romanos', 'Novo', 45, 16),
('1co', '1 Coríntios', 'Novo', 46, 16),
('2co', '2 Coríntios', 'Novo', 47, 13),
('gl', 'Gálatas', 'Novo', 48, 6),
('ef', 'Efésios', 'Novo', 49, 6),
('fp', 'Filipenses', 'Novo', 50, 4),
('cl', 'Colossenses', 'Novo', 51, 4),
('1ts', '1 Tessalonicenses', 'Novo', 52, 5),
('2ts', '2 Tessalonicenses', 'Novo', 53, 3),
('1tm', '1 Timóteo', 'Novo', 54, 6),
('2tm', '2 Timóteo', 'Novo', 55, 4),
('tt', 'Tito', 'Novo', 56, 3),
('fm', 'Filemom', 'Novo', 57, 1),
('hb', 'Hebreus', 'Novo', 58, 13),
('tg', 'Tiago', 'Novo', 59, 5),
('1pe', '1 Pedro', 'Novo', 60, 5),
('2pe', '2 Pedro', 'Novo', 61, 3),
('1jo', '1 João', 'Novo', 62, 5),
('2jo', '2 João', 'Novo', 63, 1),
('3jo', '3 João', 'Novo', 64, 1),
('jd', 'Judas', 'Novo', 65, 1),
('ap', 'Apocalipse', 'Novo', 66, 22)
ON CONFLICT (abreviacao) DO NOTHING;
